# docker-compose.yml

version: '3.8'

services:
  # Service de l'application FastAPI
  app:
    build:
      context: ./backend  # Le contexte est le dossier 'backend'
      dockerfile: Dockerfile # Le nom du Dockerfile à l'intérieur de 'backend'
    restart: unless-stopped
    depends_on:
      - db # S'assure que la base de données est démarrée avant l'application
    environment:
      # --- Configuration de la base de données ---
      # Coolify remplacera ces variables par les secrets que vous définirez
      # Le nom d'hôte 'db' est automatiquement résolu par Docker Compose
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      
      # --- Secrets d'authentification Google ---
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      
      # --- OSINT API Keys ---
      - IPINFO_API_KEY=${IPINFO_API_KEY}
      - ABUSEIPDB_API_KEY=${ABUSEIPDB_API_KEY}
      
      # --- Security Keys ---
      - FERNET_KEY=${FERNET_KEY}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - ALGORITHM=HS256 # Algorithme pour JWT
      
      # --- Configuration de l'application ---
      - FRONTEND_URL=${FRONTEND_URL} # ex: https://phishgard.paulette.usts.ai

    ports:
      - "8000:8000"
    
    # --- Section GPU (TRÈS IMPORTANT) ---
    # Votre Dockerfile utilise nvidia/cuda, il faut donc demander un GPU.
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  # Service de la base de données PostgreSQL
  db:
    image: postgres:15-alpine # Une image PostgreSQL légère et récente
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data # Persistance des données
    environment:
      # Ces variables seront à définir dans l'onglet "Secrets" de Coolify
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}

volumes:
  postgres_data: # Définit le volume pour la persistance des données